// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSl6e1S4OumCquo2LJyfapXP5XHWMfuq0',
    appId: '1:778440537102:web:1b83fbe89f5447fa83385f',
    messagingSenderId: '778440537102',
    projectId: 'petmatch-24069',
    authDomain: 'petmatch-24069.firebaseapp.com',
    storageBucket: 'petmatch-24069.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvcbNGKxAFZDK4RObefyfNmlIeIlNuli4',
    appId: '1:778440537102:android:984165f037f9ff6583385f',
    messagingSenderId: '778440537102',
    projectId: 'petmatch-24069',
    storageBucket: 'petmatch-24069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtMQyppq0i-ArQ0Q1ZKfCWExWihIhloeI',
    appId: '1:778440537102:ios:f6fa6943fd91e28583385f',
    messagingSenderId: '778440537102',
    projectId: 'petmatch-24069',
    storageBucket: 'petmatch-24069.appspot.com',
    iosBundleId: 'com.example.petmatch',
  );
}
