import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Firebase Core for initialization
import 'package:petmatch/firebase_options.dart';
import 'package:petmatch/telas/tela_login.dart';
import 'package:petmatch/telas/tela_cadastro.dart';
 // Firebase options (generated by FlutterFire CLI)
// Import your login screen here
// You can import other screens in a similar manner when you create them

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const TelaLoginWidget(), // Set LoginWidget as the initial screen
      routes: {
        '/login': (context) => const TelaLoginWidget(),
        '/signup': (context) => const TelaCadastroWidget(), // Add routes for other screens here
      },
    );
  }
}